/**
 * Build-time script: compiles preset MJML to HTML with sample slots and writes
 * preset-previews.generated.ts so the preview API route can serve HTML without
 * importing the presets module (avoids EBADF / mjml in Next.js build).
 * Run: npx tsx scripts/generate-preset-previews.ts
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { compilePreset, PRESET_IDS, PRESET_METADATA } from "../lib/reactivate/templates/presets";

const sampleByPreset: Record<string, { body: string; subheadline?: string }> = {
  browse_reminder: {
    body: "You were looking at something on our site. We saved your place. Come back anytime. If you have questions, just reply to this email.",
  },
  product_interest: {
    subheadline: "Quick recap of why visitors love this product",
    body: "Here is a quick recap of what you looked at and why it is a good fit. Key benefits: simple setup, great support, and results you can measure. Ready to pick up where you left off?",
  },
  reengagement: {
    body: "We have not seen you in a while and wanted to say hi. A few things have changed: new features, better pricing, and the same team here to help. We would love to have you back.",
  },
};

const outDir = path.join(process.cwd(), "lib", "reactivate", "templates");
const outPath = path.join(outDir, "preset-previews.generated.ts");

const SUBJECTS: Record<string, string> = {
  browse_reminder: "You left something behind",
  product_interest: "Still thinking it over?",
  reengagement: "We miss you",
};

function escapeForTsString(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$/g, "\\$")
    .replace(/\r/g, "");
}

const BODY_PLACEHOLDER = "%%%EMAIL_BODY%%%";
const htmlByPreset: Record<string, string> = {};
for (const id of PRESET_IDS) {
  const sample = sampleByPreset[id] ?? {
    body: "Your personalized message will appear here.",
  };
  const sampleSlots = {
    first_name: "there",
    body: BODY_PLACEHOLDER,
    subheadline: sample.subheadline ?? "",
    cta_text: "Back to site",
    cta_url: "https://example.com",
    cta_label: "Back to site",
    unsubscribe_url: "https://example.com/unsubscribe",
    headline: SUBJECTS[id],
    brand_name: "Your Company",
    subject: SUBJECTS[id],
  };
  const html = compilePreset(id, sampleSlots);
  htmlByPreset[id] = html;
}

const lines: string[] = [
  "// Generated by scripts/generate-preset-previews.ts - do not edit",
  "",
  "export const PRESET_IDS = [" + PRESET_IDS.map((id) => `"${id}"`).join(", ") + "] as const;",
  "",
  "export const PRESET_METADATA = " +
    JSON.stringify(PRESET_METADATA, null, 2).replace(/^/gm, "  ") + " as const;",
  "",
  "export const PRESET_PREVIEW_HTML: Record<string, string> = {",
];
for (const id of PRESET_IDS) {
  const html = htmlByPreset[id];
  lines.push(`  "${id}": \`${escapeForTsString(html)}\`,`);
}
lines.push("};");
lines.push("");
lines.push("export const PRESET_BODY_PLACEHOLDER = \"" + BODY_PLACEHOLDER + "\";");
lines.push("");

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(outPath, lines.join("\n"), "utf8");
console.log("Wrote", outPath);